[project]
name = "3-hospital-management-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "langchain>=1.2.4",
    "langchain-community>=0.4.1",
    "python-dotenv>=1.2.1",
]
